services:
  gateway-service:
    build: /shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_HOST=server-service


  server-service:
    build: /shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - postgres-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=share_it
      - DB_USER=postgres
      - DB_PASSWORD=1234


  postgres-service:
    image: postgres-15-alpine
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
